apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-prod
  labels:
    dashboards: "grafana-prod"
spec:
  config:
    log:
      mode: "console"
    security:
      admin_user: root
      admin_password: secret